-- Emit the ENTIRE dashboard payload (contract shape) as one row of nested JSON,
-- from the consolidated fact table only. Params: @from, @to (DATE).
--   bq query --location=asia-south1 --use_legacy_sql=false --format=json \
--     --parameter=from:DATE:2026-01-01 --parameter=to:DATE:2026-07-19 " $(cat snapshot_query.sql)"
WITH f AS (
  SELECT * FROM `lucirajewelry-prod.ga4_dashboard.ga4_fact_sessions`
  WHERE session_date BETWEEN @from AND @to
)
SELECT
  FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', CURRENT_TIMESTAMP()) AS generated_at,
  'bigquery_fact_table:ga4_fact_sessions' AS source,
  'INR' AS currency,
  STRUCT(CAST(@from AS STRING) AS `from`, CAST(@to AS STRING) AS `to`) AS `window`,
  (SELECT AS STRUCT
     COUNT(*) AS sessions, COUNT(DISTINCT user_pseudo_id) AS users,
     COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers,
     COUNT(DISTINCT user_pseudo_id) AS activeUsers, SUM(page_views) AS pageViews,
     COUNTIF(engaged) AS engagedSessions, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents,
     ROUND(SUM(revenue),2) AS revenue,
     ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate,
     ROUND(SAFE_DIVIDE(SUM(engagement_time_sec),COUNT(DISTINCT user_pseudo_id)),2) AS avgSessionDur,
     ROUND(SAFE_DIVIDE(SUM(engagement_time_sec),COUNT(DISTINCT user_pseudo_id)),2) AS avgEngTime,
     SUM(transactions) AS purchases, SUM(items_qty) AS itemsPurchased,
     SUM(ev_add_to_cart) AS addToCarts, SUM(ev_begin_checkout) AS checkouts
   FROM f) AS totals,
  ARRAY(SELECT AS STRUCT CAST(session_date AS STRING) AS date, COUNT(*) AS sessions,
     COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers,
     COUNT(DISTINCT user_pseudo_id) AS activeUsers, SUM(page_views) AS pageViews,
     COUNTIF(engaged) AS engagedSessions, SUM(event_count) AS eventCount,
     SUM(ev_purchase) AS purchases, SUM(key_events) AS keyEvents, ROUND(SUM(revenue),2) AS revenue
   FROM f GROUP BY session_date ORDER BY session_date) AS daily,
  [ STRUCT('view_item' AS name, (SELECT SUM(ev_view_item) FROM f) AS count),
    STRUCT('add_to_cart', (SELECT SUM(ev_add_to_cart) FROM f)),
    STRUCT('begin_checkout', (SELECT SUM(ev_begin_checkout) FROM f)),
    STRUCT('add_payment_info', (SELECT SUM(ev_add_payment) FROM f)),
    STRUCT('purchase', (SELECT SUM(ev_purchase) FROM f)) ] AS funnel,
  ARRAY(SELECT AS STRUCT channel AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 20) AS channels,
  ARRAY(SELECT AS STRUCT CONCAT(source,' / ',medium) AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 30) AS sourceMedium,
  ARRAY(SELECT AS STRUCT source AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 30) AS sources,
  ARRAY(SELECT AS STRUCT medium AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 20) AS mediums,
  ARRAY(SELECT AS STRUCT campaign AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 30) AS campaigns,
  ARRAY(SELECT AS STRUCT landing_page AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 30) AS landingPages,
  ARRAY(SELECT AS STRUCT device_category AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 10) AS devices,
  ARRAY(SELECT AS STRUCT browser AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 15) AS browsers,
  ARRAY(SELECT AS STRUCT operating_system AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 15) AS operatingSystems,
  ARRAY(SELECT AS STRUCT platform AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 10) AS platforms,
  ARRAY(SELECT AS STRUCT country AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 25) AS countries,
  ARRAY(SELECT AS STRUCT region AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 25) AS regions,
  ARRAY(SELECT AS STRUCT city AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 30) AS cities,
  ARRAY(SELECT AS STRUCT language AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 20) AS languages,
  ARRAY(SELECT AS STRUCT hostname AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 10) AS hostnames,
  ARRAY(SELECT AS STRUCT IF(is_new_user,'new','returning') AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 5) AS newReturning,
  ARRAY(SELECT AS STRUCT content_group AS name, COUNT(DISTINCT user_pseudo_id) AS users, COUNT(DISTINCT IF(is_new_user,user_pseudo_id,NULL)) AS newUsers, COUNT(*) AS sessions, COUNTIF(engaged) AS engagedSessions, ROUND(SAFE_DIVIDE(COUNTIF(engaged),COUNT(*))*100,2) AS engagementRate, SUM(page_views) AS views, SUM(event_count) AS eventCount, SUM(key_events) AS keyEvents, SUM(transactions) AS purchases, SUM(items_qty) AS items, ROUND(SUM(revenue),2) AS revenue FROM f GROUP BY name ORDER BY sessions DESC LIMIT 15) AS contentGroups,
  ARRAY(SELECT AS STRUCT p.page_path AS path, ANY_VALUE(p.page_title) AS title, SUM(p.views) AS views, COUNT(DISTINCT user_pseudo_id) AS users FROM f, UNNEST(pages) p GROUP BY path ORDER BY views DESC LIMIT 30) AS pages,
  ARRAY(SELECT AS STRUCT e.event_name AS name, SUM(e.cnt) AS count, COUNT(DISTINCT user_pseudo_id) AS users FROM f, UNNEST(events) e GROUP BY name ORDER BY count DESC LIMIT 30) AS events,
  ARRAY(SELECT AS STRUCT it.item_name AS name, ANY_VALUE(it.item_category) AS category, ANY_VALUE(it.item_brand) AS brand, SUM(IF(it.event_name='purchase',it.quantity,0)) AS items, ROUND(SUM(IF(it.event_name='purchase',it.item_revenue,0)),2) AS revenue, COUNTIF(it.event_name='view_item') AS views, COUNTIF(it.event_name='add_to_cart') AS addToCart FROM f, UNNEST(items) it GROUP BY name ORDER BY views DESC LIMIT 30) AS items
